quiz_questions_history = {
    "easy": [
        ("Who was the first President of the United States?", ["george washington", "washington"]),
        ("In which year did World War II end?", ["1945"]),
        ("Who discovered America in 1492?", ["christopher columbus", "columbus"]),
        ("Which empire was ruled by Julius Caesar?", ["roman empire", "rome"]),
        ("Who was the first man to step on the moon?", ["neil armstrong", "armstrong"]),
        ("What wall divided East and West Berlin?", ["berlin wall"]),
        ("Which country was formerly known as Persia?", ["iran"]),
        ("Who was the British queen during the Victorian era?", ["queen victoria", "victoria"]),
        ("Which ship sank in 1912 after hitting an iceberg?", ["titanic"]),
        ("What year did the American Civil War start?", ["1861"]),
        ("Who was the famous civil rights leader who delivered 'I Have a Dream'?", ["martin luther king jr", "mlk", "king"]),
        ("What ancient civilization built the pyramids?", ["egyptians", "egypt"]),
        ("Which explorer circumnavigated the globe first?", ["ferdinand magellan", "magellan"]),
        ("Which revolution began in 1789?", ["french revolution"]),
        ("Who was known as the 'Maid of Orléans'?", ["joan of arc", "jeanne d'arc"]),
        ("What was the name of the ship that carried the Pilgrims to America in 1620?", ["mayflower"]),
        ("Who wrote the Declaration of Independence?", ["thomas jefferson", "jefferson"]),
        ("Which war was fought between the North and South regions in the US?", ["american civil war"]),
        ("Who was the first emperor of China?", ["qin shi huang", "qin"]),
        ("Which ancient civilization is known for the city of Machu Picchu?", ["inca", "incas"]),
        ("Who was the leader of Nazi Germany?", ["adolf hitler", "hitler"]),
        ("Which empire was ruled by Genghis Khan?", ["mongol empire", "mongols"]),
        ("What event is known as the 'Great Fire' in 1666?", ["great fire of london"]),
        ("Who was the first female Prime Minister of the UK?", ["margaret thatcher", "thatcher"]),
        ("Which US president was assassinated in 1963?", ["john f. kennedy", "kennedy"]),
    ],

    "medium": [
        ("What year did the French Revolution begin?", ["1789"]),
        ("Who was the first emperor of Rome?", ["augustus", "octavian"]),
        ("Which war was fought from 1914 to 1918?", ["world war i", "wwi"]),
        ("Which ship was famously sunk during the Spanish-American War?", ["uss maine", "maine"]),
        ("Who was the British Prime Minister during most of World War II?", ["winston churchill", "churchill"]),
        ("Which empire did Alexander the Great conquer?", ["persian empire", "persia"]),
        ("In which year did the Berlin Wall fall?", ["1989"]),
        ("Which US president issued the Emancipation Proclamation?", ["abraham lincoln", "lincoln"]),
        ("Who was the first ruler of the Mongol Empire?", ["genghis khan", "temujin"]),
        ("Which ancient civilization built Machu Picchu?", ["inca", "incas"]),
        ("Which war was fought between Britain and the Zulu Kingdom?", ["anglo-zulu war", "zulu war"]),
        ("Who was the first person to sail around the Cape of Good Hope to India?", ["vasco da gama", "gama"]),
        ("Which battle marked Napoleon's final defeat?", ["waterloo"]),
        ("Who was the leader of the Soviet Union during World War II?", ["joseph stalin", "stalin"]),
        ("Which dynasty built the Great Wall of China?", ["qin dynasty", "qin"]),
        ("What was the main ship used by the Spanish Armada?", ["santa maria", "armada ships"]),
        ("Which revolution led to the creation of the Soviet Union?", ["russian revolution", "bolshevik revolution"]),
        ("Which year did the American Declaration of Independence get signed?", ["1776"]),
        ("Who was known as the 'Sun King'?", ["louis xiv", "louis 14"]),
        ("Which treaty ended World War I?", ["treaty of versailles", "versailles"]),
        ("Who led the Reign of Terror in France?", ["maximilien robespierre", "robespierre"]),
        ("Which explorer discovered the Pacific Ocean?", ["vasco núñez de balboa", "balboa"]),
        ("Which empire was famous for its aqueducts in Spain?", ["roman empire", "rome"]),
        ("Who wrote the Communist Manifesto?", ["karl marx", "marx"]),
        ("Which year did the Great Fire of London occur?", ["1666"]),
    ],

    "hard": [
        ("Which year did the Battle of Hastings take place?", ["1066"]),
        ("Who was the last pharaoh of ancient Egypt?", ["cleopatra", "cleopatra vii"]),
        ("Which empire was ruled by Suleiman the Magnificent?", ["ottoman empire", "ottomans"]),
        ("Which king signed the Magna Carta?", ["king john", "john"]),
        ("Which war ended with the Treaty of Westphalia?", ["thirty years war", "30 years war"]),
        ("Who was the leader of the Haitian Revolution?", ["toussaint louverture", "louverture"]),
        ("Which year did the Berlin Airlift occur?", ["1948"]),
        ("Who was the founder of the Mongol Empire?", ["genghis khan", "temujin"]),
        ("Which king was beheaded during the French Revolution?", ["louis xvi", "louis 16"]),
        ("Which empire fell in 1453 to the Ottomans?", ["byzantine empire", "byzantine"]),
        ("Who was the famous British admiral during the Napoleonic Wars?", ["horatio nelson", "nelson"]),
        ("Which war lasted from 1756 to 1763?", ["seven years war"]),
        ("Who was the first emperor of Japan?", ["jimmu", "emperor jimmu"]),
        ("Which battle marked the start of the American Revolutionary War?", ["lexington and concord", "lexington"]),
        ("Which year did the Russian Revolution occur?", ["1917"]),
        ("Which European explorer mapped the coast of Australia?", ["james cook", "cook"]),
        ("Who led the Soviet Union after Lenin?", ["joseph stalin", "stalin"]),
        ("Which dynasty ruled China during the Ming period?", ["ming dynasty", "ming"]),
        ("Which battle was the turning point in the Pacific during WWII?", ["midway", "battle of midway"]),
        ("Who assassinated Archduke Franz Ferdinand?", ["gavrilo princip", "princip"]),
        ("Which year did the Spanish Civil War begin?", ["1936"]),
        ("Who was the founder of the Mughal Empire in India?", ["babur"]),
        ("Which king ruled England during the Spanish Armada?", ["queen elizabeth i", "elizabeth i"]),
        ("Which empire controlled Constantinople before 1453?", ["byzantine empire", "byzantines"]),
        ("Which war ended with the Peace of Paris in 1763?", ["seven years war"]),
    ],

    "challenge": [
        ("Which year did the fall of Constantinople occur?", ["1453"]),
        ("Who was the first President of the Republic of Turkey?", ["mustafa kemal ataturk", "ataturk"]),
        ("Which treaty ended the Napoleonic Wars?", ["treaty of paris", "paris"]),
        ("Who was the first ruler of the Holy Roman Empire?", ["charlemagne"]),
        ("Which battle is considered Napoleon's greatest victory?", ["battle of austerlitz", "austerlitz"]),
        ("Which queen ruled England for 63 years and oversaw the Spanish Armada?", ["queen elizabeth i", "elizabeth i"]),
        ("Who was the founder of modern geology?", ["james hutton", "hutton"]),
        ("Which Chinese dynasty built the Forbidden City?", ["ming dynasty", "ming"]),
        ("Who was the pharaoh during the Exodus according to tradition?", ["ramesses ii", "ramses ii"]),
        ("Which city was the capital of the Byzantine Empire?", ["constantinople", "istanbul"]),
        ("Which treaty ended the Thirty Years War?", ["treaty of westphalia", "westphalia"]),
        ("Who led the Bolsheviks during the Russian Revolution?", ["vladimir lenin", "lenin"]),
        ("Which empire was known for the construction of Machu Picchu?", ["inca empire", "inca"]),
        ("Which year did the Berlin Wall fall?", ["1989"]),
        ("Who wrote the history of the Peloponnesian War?", ["thucydides"]),
        ("Which battle ended Napoleon's rule?", ["battle of waterloo", "waterloo"]),
        ("Which ancient city was buried by the eruption of Mount Vesuvius?", ["pompeii"]),
        ("Who was the British Prime Minister during most of World War II?", ["winston churchill", "churchill"]),
        ("Which dynasty ruled China during the construction of the Great Wall?", ["qin dynasty", "qin"]),
        ("Who was the last Tsar of Russia?", ["nicholas ii", "tsar nicholas ii"]),
        ("Which civilization invented cuneiform writing?", ["sumerians", "sumer"]),
        ("Who led the Norman conquest of England?", ["william the conqueror", "william i"]),
        ("Which empire was known as the 'Land of the Rising Sun'?", ["japan", "japanese empire"]),
        ("Which battle was the turning point in the American Civil War?", ["gettysburg", "battle of gettysburg"]),
        ("Who initiated the Protestant Reformation?", ["martin luther", "luther"]),
    ]
}
