quiz_questions_general = {
    "easy": [
        ("What is the capital of France?", ["paris"]),
        ("How many continents are there on Earth?", ["7", "seven"]),
        ("What color do you get when you mix red and white?", ["pink"]),
        ("Which animal is known as man's best friend?", ["dog"]),
        ("What is the largest ocean on Earth?", ["pacific ocean", "pacific"]),
        ("What is 5 + 7?", ["12", "twelve"]),
        ("Which planet is closest to the Sun?", ["mercury"]),
        ("What do bees make?", ["honey"]),
        ("Which country is famous for the Eiffel Tower?", ["france"]),
        ("What is the main ingredient in bread?", ["flour"]),
        ("What do you call frozen water?", ["ice"]),
        ("Which holiday celebrates independence in the United States?", ["independence day", "4th of july", "fourth of july"]),
        ("What is the largest mammal on Earth?", ["blue whale", "whale"]),
        ("How many days are in a leap year?", ["366"]),
        ("Which fruit is yellow and curved?", ["banana"]),
        ("What is the capital of England?", ["london"]),
        ("Which sport uses a ball and a bat?", ["baseball"]),
        ("What gas do humans exhale?", ["carbon dioxide", "co2"]),
        ("Which month comes after June?", ["july"]),
        ("What is the square root of 16?", ["4", "four"]),
        ("Which shape has three sides?", ["triangle"]),
        ("What do you call a baby cat?", ["kitten"]),
        ("Which direction does the sun rise from?", ["east"]),
        ("What is 10 minus 4?", ["6", "six"]),
        ("What is the color of the sky on a clear day?", ["blue"]),
    ],

    "medium": [
        ("Which ocean is on the east coast of the United States?", ["atlantic ocean", "atlantic"]),
        ("What is the capital of Japan?", ["tokyo"]),
        ("How many players are on a standard soccer team on the field?", ["11", "eleven"]),
        ("What is the chemical symbol for water?", ["h2o"]),
        ("Which continent is Egypt located in?", ["africa"]),
        ("What is the tallest mountain in the world?", ["mount everest", "everest"]),
        ("Which country is famous for sushi?", ["japan"]),
        ("What is the largest desert on Earth?", ["sahara desert", "sahara"]),
        ("How many legs does a spider have?", ["8", "eight"]),
        ("Which language is primarily spoken in Brazil?", ["portuguese"]),
        ("What is the main ingredient in sushi?", ["rice"]),
        ("Which U.S. state is famous for Hollywood?", ["california"]),
        ("What is the capital of Canada?", ["ottawa"]),
        ("Which European city is known for the Colosseum?", ["rome"]),
        ("What gas do humans breathe in to survive?", ["oxygen"]),
        ("Which planet is known as the Gas Giant?", ["jupiter"]),
        ("Who wrote 'Romeo and Juliet'?", ["william shakespeare", "shakespeare"]),
        ("Which animal is known for its black and white stripes?", ["zebra"]),
        ("How many sides does a hexagon have?", ["6", "six"]),
        ("Which U.S. president issued the Emancipation Proclamation?", ["abraham lincoln", "lincoln"]),
        ("Which ocean is on the west coast of Africa?", ["atlantic ocean", "atlantic"]),
        ("Which fruit is red and often associated with keeping doctors away?", ["apple"]),
        ("What is the capital of Australia?", ["canberra"]),
        ("Which country is known as the Land of the Rising Sun?", ["japan"]),
        ("Which element has the chemical symbol 'O'?", ["oxygen"]),
    ],

    "hard": [
        ("Which country has the most time zones?", ["france"]),
        ("What is the smallest country in the world by area?", ["vatican city", "vatican"]),
        ("Which country has the most pyramids?", ["sudan"]),
        ("What is the largest island in the world?", ["greenland"]),
        ("Which planet has the most moons?", ["saturn"]),
        ("Which country has the highest population in the world?", ["china"]),
        ("Which river is the longest in the world?", ["nile"]),
        ("What is the capital of Iceland?", ["reykjavik"]),
        ("Which European country is famous for its fjords?", ["norway"]),
        ("Which desert is the largest hot desert on Earth?", ["sahara"]),
        ("What is the capital of New Zealand?", ["wellington"]),
        ("Which element has the highest melting point?", ["tungsten"]),
        ("Which country invented paper?", ["china"]),
        ("Which city is called the 'City of a Hundred Spires'?", ["prague"]),
        ("What is the national animal of Canada?", ["beaver"]),
        ("Which U.S. state is known as the 'Land of 10,000 Lakes'?", ["minnesota"]),
        ("Which country uses the rupee as its currency?", ["india", "pakistan", "sri lanka"]),
        ("Which organ in the human body produces bile?", ["liver"]),
        ("Which sea creature has three hearts?", ["octopus"]),
        ("Which country is known as the 'Emerald Isle'?", ["ireland"]),
        ("Which is the smallest continent by land area?", ["australia"]),
        ("Which country is known for its maple syrup?", ["canada"]),
        ("Which gas is used to fill balloons to make them float?", ["helium"]),
        ("Which country gifted the Statue of Liberty to the USA?", ["france"]),
        ("Which U.S. state is the Grand Canyon located in?", ["arizona"]),
    ],

    "challenge": [
        ("Which country has the most UNESCO World Heritage Sites?", ["italy"]),
        ("Which planet has the longest day?", ["venus"]),
        ("Which city hosted the 1936 Summer Olympics?", ["berlin"]),
        ("Which ancient civilization built the city of Petra?", ["nabateans", "nabataean"]),
        ("Which is the deepest point in Earth's oceans?", ["mariana trench", "the mariana trench"]),
        ("Which war was fought between the Allies and Axis powers?", ["world war ii", "wwii"]),
        ("Which country is the largest by area in Africa?", ["algeria"]),
        ("Which U.S. president served the shortest term?", ["william henry harrison", "harrison"]),
        ("Which country consumes the most chocolate per capita?", ["switzerland"]),
        ("Which city is home to the Sagrada Familia?", ["barcelona"]),
        ("Which country has the most volcanoes?", ["indonesia"]),
        ("Which country is the largest producer of coffee?", ["brazil"]),
        ("Which country has the most spoken languages?", ["papua new guinea", "png"]),
        ("Which element has the atomic number 79?", ["gold", "au"]),
        ("Which European country has the highest number of lakes?", ["finland"]),
        ("Which is the longest river in Europe?", ["volga"]),
        ("Which Asian country is known as the Land of the Rising Sun?", ["japan"]),
        ("Which city is known as the 'Big Apple'?", ["new york city", "nyc", "new york"]),
        ("Which is the largest bay in the world?", ["hudson bay"]),
        ("Which African country has the most pyramids?", ["sudan"]),
        ("Which planet is known for its rings?", ["saturn"]),
        ("Which country invented pizza?", ["italy"]),
        ("Which ancient wonder was located in Egypt?", ["great pyramid of giza", "pyramids"]),
        ("Which ocean borders the west coast of South America?", ["pacific ocean", "pacific"]),
        ("Which country is home to the Great Barrier Reef?", ["australia"]),
    ]
}
