quiz_questions_science = {
    "easy": [
        ("What planet is known as the Red Planet?", ["mars"]),
        ("What gas do plants breathe in during photosynthesis?", ["carbon dioxide", "co2"]),
        ("What is H2O commonly known as?", ["water"]),
        ("What force pulls objects toward Earth?", ["gravity"]),
        ("What gas do humans need to breathe?", ["oxygen"]),
        ("What planet do we live on?", ["earth"]),
        ("What galaxy is Earth located in?", ["milky way", "the milky way"]),
        ("What organ pumps blood around the body?", ["heart"]),
        ("What vitamin do we get from sunlight?", ["vitamin d", "d"]),
        ("What part of the plant carries water from the roots?", ["stem"]),
        ("How many legs does an insect have?", ["6", "six"]),
        ("What is the centre of an atom called?", ["nucleus"]),
        ("What is the process of water turning into gas called?", ["evaporation"]),
        ("What is the hottest planet in our solar system?", ["venus"]),
        ("What material are human nails made of?", ["keratin"]),
        ("What is the largest planet in our solar system?", ["jupiter"]),
        ("What do bees collect from flowers?", ["pollen", "nectar"]),
        ("What is the study of living things called?", ["biology"]),
        ("What do you call animals that only eat plants?", ["herbivores"]),
        ("What is the closest star to Earth?", ["the sun", "sun"]),
        ("What part of the cell contains DNA?", ["nucleus"]),
        ("What do plants release into the air?", ["oxygen"]),
        ("What sense organ allows us to see?", ["eyes"]),
        ("What is frozen water called?", ["ice"]),
        ("How many states of matter are there traditionally?", ["3", "three", "solid liquid gas"]),
    ],

    "medium": [
        ("What gas makes up most of Earth's atmosphere?", ["nitrogen"]),
        ("What is the chemical symbol for gold?", ["au"]),
        ("What part of the brain controls memory?", ["hippocampus"]),
        ("What unit is used to measure force?", ["newton", "n"]),
        ("What is the speed of light (approx km/s)?", ["300000", "300,000", "3e5"]),
        ("What is the main gas responsible for climate change?", ["carbon dioxide", "co2"]),
        ("What organ filters blood in the human body?", ["kidneys", "kidney"]),
        ("What pigment gives plants their green color?", ["chlorophyll"]),
        ("What blood cells fight infection?", ["white blood cells", "leukocytes"]),
        ("What part of the Earth is liquid metal?", ["outer core"]),
        ("What scientist proposed the three laws of motion?", ["isaac newton", "newton"]),
        ("What type of energy is stored in food?", ["chemical energy", "chemical"]),
        ("What organelle is known as the powerhouse of the cell?", ["mitochondria"]),
        ("What metal is liquid at room temperature?", ["mercury"]),
        ("What is the most abundant element in the universe?", ["hydrogen"]),
        ("What type of rock is formed from cooled lava?", ["igneous"]),
        ("What process allows plants to make their own food?", ["photosynthesis"]),
        ("What is the smallest unit of life?", ["cell"]),
        ("What force keeps planets in orbit around the sun?", ["gravity"]),
        ("What is the boiling point of water in Celsius?", ["100", "100c", "100°c"]),
        ("What blood type is known as the universal donor?", ["o negative", "o-"]),
        ("What is the chemical formula for table salt?", ["nacl"]),
        ("What is the human body's largest organ?", ["skin"]),
        ("What is the study of earthquakes called?", ["seismology"]),
        ("What is the second planet from the sun?", ["venus"]),
    ],

    "hard": [
        ("What particle has a negative charge?", ["electron"]),
        ("What is the heaviest naturally occurring element?", ["uranium"]),
        ("What scale measures the hardness of minerals?", ["mohs scale", "mohs"]),
        ("What is the 2nd law of thermodynamics about?", ["entropy", "increase in entropy"]),
        ("What is the powerhouse of bacterial cells?", ["they don't have mitochondria", "none"]),
        ("What process do cells use to divide for growth?", ["mitosis"]),
        ("What is the chemical symbol for lead?", ["pb"]),
        ("What is the name of the bond between water molecules?", ["hydrogen bond"]),
        ("What type of galaxy is the Milky Way?", ["spiral galaxy", "spiral"]),
        ("What organ stores bile?", ["gallbladder"]),
        ("What is the smallest particle of an element?", ["atom"]),
        ("What is the pH of pure water?", ["7", "seven"]),
        ("What is the study of fungi called?", ["mycology"]),
        ("What is ATP used for in cells?", ["energy", "cell energy"]),
        ("What scientist discovered penicillin?", ["alexander fleming", "fleming"]),
        ("What does DNA stand for?", ["deoxyribonucleic acid"]),
        ("What gas makes up about 21% of Earth's atmosphere?", ["oxygen"]),
        ("What organ produces insulin?", ["pancreas"]),
        ("What is the universal solvent?", ["water"]),
        ("What type of bond shares electrons?", ["covalent bond", "covalent"]),
        ("What is the most reactive metal?", ["francium"]),
        ("What part of the brain controls balance?", ["cerebellum"]),
        ("What vitamin is also known as ascorbic acid?", ["vitamin c", "c"]),
        ("What is the speed of sound in air (approx m/s)?", ["343", "340"]),
        ("What is the largest internal organ?", ["liver"]),
    ],

    "challenge": [
        ("What theory explains the origin of the universe?", ["big bang theory", "big bang"]),
        ("What is Schrödinger famous for?", ["schrodinger's cat", "quantum mechanics"]),
        ("What is the heaviest ELEMENT in the human body?", ["iodine"]),
        ("What is Planck's constant (approx value)?", ["6.63e-34", "6.6e-34"]),
        ("What is the name of the particle that gives mass to others?", ["higgs boson"]),
        ("What does E = mc^2 represent?", ["mass-energy equivalence", "energy equals mass times speed of light squared"]),
        ("What organelle performs protein synthesis?", ["ribosomes"]),
        ("What branch of math is used heavily in quantum physics?", ["linear algebra"]),
        ("What is Heisenberg's uncertainty principle about?", ["cannot know position and momentum simultaneously"]),
        ("What astronomical event occurs when a star collapses?", ["supernova"]),
        ("What type of radiation has the shortest wavelength?", ["gamma radiation", "gamma rays"]),
        ("What is the rarest blood type?", ["ab negative", "ab-"]),
        ("What is the chemical formula for ozone?", ["o3"]),
        ("What type of cell division creates gametes?", ["meiosis"]),
        ("What is the approximate age of the Earth (in billions)?", ["4.5", "4.54"]),
        ("What is the term for water in all three states existing together?", ["triple point"]),
        ("What metal has the highest electrical conductivity?", ["silver"]),
        ("What is the only letter not found in the periodic table?", ["j"]),
        ("What astronomer proved the Milky Way is rotating?", ["bertil lindblad", "lindblad"]),
        ("What mechanism drives evolution?", ["natural selection"]),
        ("What vitamin deficiency causes scurvy?", ["vitamin c", "c"]),
        ("What is the study of the universe called?", ["cosmology"]),
        ("What is the most common isotope of carbon?", ["carbon-12", "c-12"]),
        ("What field studies the behavior of subatomic particles?", ["quantum physics", "quantum mechanics"]),
        ("What is the term for atoms of the same element with different numbers of neutrons?", ["isotopes"]),
    ]
}
