quiz_questions_sport = {
    "easy": [
        ("How many players are on a football (soccer) team on the field?", ["11", "eleven"]),
        ("Which sport uses a shuttlecock?", ["badminton"]),
        ("In basketball, how many players from one team are on court at a time?", ["5", "five"]),
        ("What is the term for a score of zero in tennis?", ["love"]),
        ("How many bases are there in baseball?", ["4", "four"]),
        ("Which sport uses a puck?", ["ice hockey", "hockey"]),
        ("In which sport can you get a 'hole-in-one'?", ["golf"]),
        ("How long is an Olympic long-course swimming pool in metres?", ["50", "50m", "50 metres", "50 meters"]),
        ("How many minutes are in a standard professional football (soccer) match (excluding extra time)?", ["90", "ninety", "90 minutes"]),
        ("What surface is the Wimbledon tennis tournament played on?", ["grass"]),
        ("How many players are on the court for a volleyball team?", ["6", "six"]),
        ("How many points is a try worth in rugby union?", ["5", "five"]),
        ("Which country invented judo?", ["japan"]),
        ("How many holes are there in a standard full golf course?", ["18", "eighteen"]),
        ("How many periods (quarters) are in an NBA game?", ["4", "four"]),
        ("How many players are on an ice hockey team on the ice at once (per side)?", ["6", "six"]),
        ("Which sport uses the term 'strike' and 'spare'?", ["bowling"]),
        ("What is the common name for association football in the United States?", ["soccer"]),
        ("Which sport is associated with the Tour de France?", ["cycling"]),
        ("What sport awards a 'century' for scoring 100 runs?", ["cricket"]),

        # NEW EASY QUESTIONS (5)
        ("What sport uses a bat and a ball and is popular in England and India?", ["cricket"]),
        ("In football (soccer), what part of the body cannot be used (except the goalkeeper)?", ["hands"]),
        ("Which sport uses a net, a ball, and a racket?", ["tennis"]),
        ("What piece of equipment do you need to play baseball?", ["bat", "baseball bat"]),
        ("Which sport takes place on a running track?", ["athletics", "running", "track and field"]),
    ],

    "medium": [
        ("In what year were the first modern Olympic Games held?", ["1896"]),
        ("Which country won the very first FIFA World Cup in 1930?", ["uruguay"]),
        ("How many minutes does a standard professional boxing round usually last?", ["3", "three"]),
        ("What is the height of an NBA basketball rim above the floor?", ["10 feet", "10ft", "10'"]),
        ("How many points does a winner receive in the current Formula 1 championship points system?", ["25", "twenty five"]),
        ("How many events are contested in a decathlon?", ["10", "ten"]),
        ("What is the maximum score in a single perfect game of ten-pin bowling?", ["300", "three hundred"]),
        ("How many players are on a rugby league team on the field?", ["13", "thirteen"]),
        ("How many players make up a cricket team on the field?", ["11", "eleven"]),
        ("How long (minutes) is a professional football match in the NFL (excluding overtime)?", ["60", "sixty", "60 minutes"]),
        ("Which Grand Slam tennis tournament is played on clay?", ["french open", "roland garros", "frenchopen"]),
        ("How many yards long is an American football field including both end zones?", ["120", "120 yards"]),
        ("How many minutes are in a standard NHL hockey game (three periods)?", ["60", "sixty", "60 minutes"]),
        ("How many sets are men's singles matches at Wimbledon played to (Grand Slam, non-olympic)?", ["best of 5", "5", "five"]),
        ("How many meters is an Olympic marathon?", ["42.195", "42.195 km", "26.2 miles"]),
        ("Which country has won the most Cricket World Cups (men's ODI) historically?", ["australia"]),
        ("How many players are on a water polo team in the pool at one time per side?", ["7", "seven"]),
        ("Which athlete won eight gold medals at the 2008 Beijing Olympics in swimming?", ["michael phelps", "phelps"]),
        ("Which race is known as the oldest annual cycling race in the world, held in Belgium?", ["tour of flanders", "tourofflanders"]),
        ("Which country hosted the 2016 Summer Olympics?", ["brazil"]),

        # NEW MEDIUM QUESTIONS (5)
        ("How long is a standard tennis court from baseline to baseline?", ["78 feet", "78ft"]),
        ("Which nation has won the most Olympic gold medals overall?", ["usa", "united states"]),
        ("In Formula 1, how many drivers race for each team?", ["2", "two"]),
        ("How many players are on a standard lacrosse team on the field?", ["10", "ten"]),
        ("In cricket, how many balls are in an over?", ["6", "six"]),
    ],

    "hard": [
        ("What is the official weight of a men's competition shot put (in kg)?", ["7.26", "7.26kg", "7.26 kg"]),
        ("What is the diameter of a regulation basketball hoop (in inches)?", ["18", "18 inches"]),
        ("Who won the FIFA World Cup in 1966?", ["england"]),
        ("What is the fencing weapon where hits are scored with the tip only and the valid target is the torso?", ["foil"]),
        ("What is the term for taking three wickets in three consecutive deliveries in cricket?", ["hat-trick", "hattrick"]),
        ("Which nation has won the most Rugby World Cups as of 2025?", ["new zealand", "nz"]),
        ("What year did Roger Bannister first break the four-minute mile?", ["1954"]),
        ("How many total yards are in a regulation American football end zone (depth)?", ["10", "ten"]),
        ("In cycling, how many Grand Tours are there each year?", ["3", "three"]),
        ("Which country hosted the first modern Olympic Games in 1896?", ["greece"]),
        ("What is the standard length (metres) of an Olympic rowing course?", ["2000", "2000m", "2000 metres"]),
        ("How many Olympic rings are there in the official symbol?", ["5", "five"]),
        ("What is the maximum number of substitutions allowed in a single FIFA World Cup match (recent era)?", ["5", "five"]),
        ("In tennis scoring, what point comes after 40–40 if a player wins the next point?", ["advantage", "ad"]),
        ("What is the official distance of an Olympic steeplechase race for men (in metres)?", ["3000", "3000m", "3000 metres"]),
        ("Which team has won the most UEFA Champions League titles historically?", ["real madrid"]),
        ("What metal is the Olympic gold medal primarily made of?", ["silver"]),
        ("How many players are on a handball team on court per side?", ["7", "seven"]),
        ("Which sport introduced the VAR system at top professional levels?", ["football", "soccer"]),
        ("What is the weight of a regulation men's Olympic discus?", ["2kg", "2 kg"]),
        ("In snooker, how many points is the blue ball worth?", ["5", "five"]),
        ("How many meters is the standard velodrome cycling track?", ["250", "250m"]),
        ("What is the total distance of an Ironman triathlon marathon leg?", ["42.195 km", "42.195"]),
        ("Which country has won the most Olympic volleyball gold medals (men's indoor)?", ["soviet union", "ussr"]),
    ],

    "challenge": [
        ("Which boxer was known as 'The Greatest' and won Olympic gold in 1960?", ["muhammad ali", "cassius clay"]),
        ("What is the fastest recorded 100m sprint time under legal wind conditions?", ["9.58", "usain bolt 9.58"]),
        ("Which footballer scored the fastest hat-trick in Premier League history?", ["sadio mane", "sadio mané"]),
        ("Who is the only athlete to win Olympic gold in both Summer and Winter Games?", ["none", "no one"]),
        ("Which country won the first Rugby World Cup in 1987?", ["new zealand", "nz"]),
        ("Who ran the first official sub-4-minute mile?", ["roger bannister", "bannister"]),
        ("Which tennis player completed the calendar-year Grand Slam most recently?", ["steffi graf", "steffi graf 1988"]),
        ("What is the highest number of gold medals won by a single athlete at one Olympic Games?", ["8", "michael phelps"]),
        ("Which golfer has the most major championship wins?", ["jack nicklaus", "nicklaus"]),
        ("Which team completed the football treble in 1999?", ["manchester united", "man utd", "manu"]),
        ("What is the maximum allowable wind assistance for a sprint record?", ["2.0", "2 m/s", "2.0m/s"]),
        ("Which cricketer has the most international centuries (as of 2023)?", ["virat kohli", "kohli"]),
        ("Who holds the world record in the men's pole vault?", ["mondo duplantis", "armand duplantis"]),
        ("What is the record for the longest tennis match ever played?", ["11 hours 5 minutes", "11h 5m"]),
        ("Who won the first ever Ballon d'Or award?", ["stanley matthews", "matthews"]),
        ("Which country has the most Olympic medals of all time?", ["usa", "united states"]),
        ("Who holds the record for most home runs in a single MLB season?", ["barry bonds"]),
        ("Which chess player held the world championship title for 15 years straight?", ["garry kasparov", "kasparov"]),
        ("Who is the only driver to win the F1 championship without winning a race that season?", ["keke rosberg", "rosberg"]),
        ("What is the longest verified golf drive in competition?", ["515 yards"]),
        ("Which nation has appeared in the most FIFA World Cup tournaments?", ["brazil"]),
        ("Who holds the record for the fastest serve in men's tennis?", ["sam groth"]),
        ("Who has the most NBA championships as a player?", ["bill russell", "russell"]),
        ("What country won the first ever Cricket World Cup?", ["west indies", "windies"]),
        ("Which athlete has the longest undefeated streak in professional boxing?", ["floyd mayweather", "mayweather"]),
    ]
}
